name: Test, compile and push python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-publish:
    name: Test, compile and push python package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: x64

      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel twine

      - name: Build package
        run: >-
          python 
          setup.py 
          sdist 
          bdist_wheel

      - name: Publish to PyPi Test
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_KEY }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to production PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PROD_PYPI_KEY }}
