name: Test, compile and push python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-publish:
    name: Test, compile and push python package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: x64

      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ env.GITHUB_REPOSITORY_OWNER }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_KEY }}
        run: |
            python setup.py sdist bdist_wheel
            twine upload --repository testpypi dist/*